name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build
        run: |
          echo "Building site..."

      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          headers: |
            Cache-Control: max-age=31536000, public
            Access-Control-Allow-Origin: *